// ── utils/exporters/exportHTML.js ─────────────────────────────────────────────
import { downloadFile, getFilename } from "./exportHelpers.js";

export function generateHTML(filteredData, selectedSites) {
  const filename = getFilename(selectedSites, "html");

  const cards = filteredData.map(({ url, data }) => {
    const notes = ["important", "medium", "normal"].flatMap((priority) =>
      (data[priority] || []).map((note) => `
        <div class="note priority-${priority}">
          ${note.img ? `<img src="${note.img}" alt="note image">` : ""}
          <p class="note-text">${note.note || "N/A"}</p>
          <div class="note-footer">
            <span class="priority-tag">${priority.toUpperCase()}</span>
            <span class="note-date">${note.createdAt}</span>
          </div>
        </div>
      `)
    ).join("");
    return `
      <div class="site-section">
        <h2>${url}</h2>
        <div class="notes-grid">${notes}</div>
      </div>
    `;
  }).join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>TheWebNote Export</title>
  <style>
    body { font-family: 'Segoe UI', sans-serif; background: #f8fafc; color: #1e293b; padding: 40px; }
    header { background: #3b82f6; color: #fff; padding: 16px 40px; margin: -40px -40px 40px; display: flex; justify-content: space-between; align-items: center; }
    header h1 { font-size: 20px; margin: 0; }
    header span { font-size: 13px; opacity: 0.85; }
    h2 { font-size: 18px; margin-bottom: 16px; color: #3b82f6; }
    .site-section { margin-bottom: 40px; }
    .notes-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; }
    .note { border-radius: 12px; padding: 16px; border: 2px solid #e2e8f0; background: #fff; }
    .note img { width: 100%; border-radius: 8px; margin-bottom: 10px; object-fit: cover; max-height: 160px; }
    .note-text { font-size: 14px; margin-bottom: 12px; }
    .note-footer { display: flex; justify-content: space-between; font-size: 12px; color: #94a3b8; }
    .priority-tag { font-weight: 700; }
    .priority-important { border-color: #ef4444; background: #fef2f2; }
    .priority-medium { border-color: #eab308; background: #fefce8; }
    .priority-normal { border-color: #e2e8f0; background: #fff; }
    footer { margin-top: 60px; text-align: center; font-size: 12px; color: #94a3b8; }
  </style>
</head>
<body>
  <header>
    <h1>📝 TheWebNote</h1>
    <span>Exported on ${new Date().toLocaleDateString()}</span>
  </header>
  ${cards}
  <footer>Generated by TheWebNote — your notes, your device.</footer>
</body>
</html>`;

  downloadFile(filename, html, "text/html");
}